baseurl: ""

# Site settings
title: Liz + Craig - July 16, 2016
email: your-email@domain.com
description: "The website for the wedding of Liz Wyckoff and Craig Eley in Letchworth State Park, New York, on July 16, 2016."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F29864
  secondary: F8B66C  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Liz Wyckoff
  pic: 1
  position: The Bride
  social:
    - title: twitter
      url: http://twitter.com/elizwyckoff
    - title: instagram
      url: https://www.instagram.com/elizwyckoff
    - title: envelope
      url: mailto:elizabeth.wyckoff@gmail.com?subject=Wedding

- name: Craig Eley
  pic: 2
  position: The Groom
  social:
    - title: twitter
      url: http://twitter.com/craigeley
    - title: instagram
      url: http://instagram.com/craigeley
    - title: envelope
      url: mailto:craigeley@gmail.com?subject=Wedding


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/search?q=%23lizpluscraig
  - title: instagram
    url: https://instagram.com/explore/tags/lizpluscraig/
  - title: github
    url: https://github.com/craigeley/agency_wedding/tree/gh-pages
    
# Postal address (add as many lines as necessary)
address:
  - line: 734 Jenifer St.
  - line: Madison, WI 53703

# Build settings
markdown: kramdown
permalink: pretty